#!/usr/bin/env php
<?php

use LifeSpikes\SSR\Application;
use LifeSpikes\SSR\BuildTools\Commands\InstallDependencies;
use LifeSpikes\SSR\BuildTools\Commands\DiagnoseDependencies;

const SSR_APP_ROOT = __DIR__;

require_once 'vendor/autoload.php';

try {
    $console = ($application = new Application())->console;
    $commands = [
        new InstallDependencies($application),
        new DiagnoseDependencies($application),
    ];

    foreach ($commands as $command) {
        $console->add($command);
    }

    $application->terminal();
} catch (Exception $e) {
}
